version: 0.0.{build}
image: Visual Studio 2017
platform:
- Win32
- x64
configuration: Release
install:
- ps: (New-Object System.Net.WebClient).DownloadFile("https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-windows.zip", "C:\projects\hedgelib\premake.zip")
- ps: Expand-Archive -LiteralPath C:\projects\hedgelib\premake.zip -DestinationPath C:\projects\hedgelib\
- cmd: premake5 vs2017
build:
  project: HedgeLib.sln
  verbosity: minimal
artifacts:
- path: HedgeLib/bin/x86/Release
  name: HedgeLib (Windows x86)
- path: HedgeLib/bin/x64/Release
  name: HedgeLib (Windows x64)
- path: HedgeEdit/bin/x86/Release
  name: HedgeEdit (Windows x86)
- path: HedgeEdit/bin/x64/Release
  name: HedgeEdit (Windows x64)
- path: HedgeTools/HedgeArcPack/bin/x86/Release
  name: HedgeArcPack (Windows x86)
- path: HedgeTools/HedgeArcPack/bin/x64/Release
  name: HedgeArcPack (Windows x64)