version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  project: HedgeLib.sln
  verbosity: minimal
artifacts:
- path: HedgeLib/bin/Release
  name: HedgeLib
- path: HedgeEdit/bin/Release
  name: HedgeEdit
- path: HedgeTools/HedgeGISMEditor/bin/Release
  name: HedgeGISMEditor
- path: HedgeTools/HedgeArchiveEditor/bin/Release
  name: HedgeArchiveEditor
- path: HedgeTools/HedgeArcPack/bin/Release
  name: HedgeArcPack
- path: HedgeTools/HedgePFD/bin/Release
  name: HedgePFD
- path: HedgeTools/ForcesGISMEditor/bin/Release
  name: ForcesGISMEditor
- path: HedgeTools/HedgeCnvrsEditor/bin/Release
  name: HedgeCnvrsEditor
- path: HedgeTools/ForcesSCFNTConverter/bin/Release
  name: ForcesSCFNTConverter