version: 0.0.{build}
image:
- Visual Studio 2019
- Ubuntu1804
platform:
- Win32
- x86
- x64
configuration: Release
matrix:
  exclude:
    - platform: x86
      image: Visual Studio 2019
    - platform: Win32
      image: Ubuntu1804

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - ps: (New-Object System.Net.WebClient).DownloadFile("https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-windows.zip", "C:\projects\hedgelib\premake.zip")
    - ps: Expand-Archive -LiteralPath C:\projects\hedgelib\premake.zip -DestinationPath C:\projects\hedgelib\
    - ps: Set-Content -Path C:\projects\hedgelib\hedgeedit\depends.lua -Value 'return { QtDir32 = "C:/Qt/5.13/msvc2017", QtDir64 = "C:/Qt/5.13/msvc2017_64" }'
    - cmd: premake5 vs2019 --type=shared
  build:
    project: HedgeLib.sln
    verbosity: minimal
  after_build:
    - ps: |
        $projects = "HedgeEdit","HedgeLib","HedgeTools\HedgeArcPack","HedgeTools\HedgeOffsets"
        $dir = "C:\projects\hedgelib"
        if ($env:PLATFORM -imatch "Win32") {
          foreach ($project in $projects) {
            Rename-Item $dir\$project\bin\x86 $dir\$project\bin\Win32
          }
        }
        Copy-Item "$dir\hedgelib\include" -Destination "$dir\hedgelib\bin\$env:PLATFORM\Release\include" -Recurse
        foreach ($project in $projects) {
          robocopy /xc /xn /xo /nfl /njh /njs /ndl "$dir" "$dir\$project\bin\$env:PLATFORM\Release" License.txt
          del $dir\$project\bin\$env:PLATFORM\Release\*.iobj
          del $dir\$project\bin\$env:PLATFORM\Release\*.ipdb
          del $dir\$project\bin\$env:PLATFORM\Release\*.pdb
        }
  artifacts:
    - path: HedgeEdit/bin/$(PLATFORM)/Release
      name: HedgeEdit
    - path: HedgeLib/bin/$(PLATFORM)/Release
      name: HedgeLib
    - path: HedgeTools/HedgeArcPack/bin/$(PLATFORM)/Release
      name: HedgeArcPack
    - path: HedgeTools/HedgeOffsets/bin/$(PLATFORM)/Release
      name: HedgeOffsets
-
  matrix:
    only:
      - image: Ubuntu1804

  install:
    - ps: (New-Object System.Net.WebClient).DownloadFile("https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz", "/home/appveyor/projects/hedgelib/premake.tar.gz")
    - sh: tar -zvxf /home/appveyor/projects/hedgelib/premake.tar.gz -C /home/appveyor/projects/hedgelib
    - sh: /home/appveyor/projects/hedgelib/premake5 gmake2 --type=shared
    - sh: sudo apt-get update
    - sh: sudo apt-get install -yq gcc-8-multilib g++-8-multilib
  build: off
  build_script:
    - sh: make CPP=g++-8 CXX=g++-8 LD=g++-8 config=release_$PLATFORM
    - ps: |
        $projects = "HedgeLib","HedgeTools/HedgeArcPack","HedgeTools/HedgeOffsets"
        $dir = "/home/appveyor/projects/hedgelib"
        Copy-Item "$dir/HedgeLib/include" -Destination "$dir/HedgeLib/bin/$env:PLATFORM/Release/include" -Recurse
        foreach ($project in $projects) {
          cp -n "$dir/License.txt" "$dir/$project/bin/$env:PLATFORM/Release/License.txt"
        }
  artifacts:
    - path: HedgeLib/bin/$(PLATFORM)/Release
      name: HedgeLib
    - path: HedgeTools/HedgeArcPack/bin/$(PLATFORM)/Release
      name: HedgeArcPack
    - path: HedgeTools/HedgeOffsets/bin/$(PLATFORM)/Release
      name: HedgeOffsets
