version: 0.0.{build}
image: Visual Studio 2017
platform:
- Win32
- x64
configuration: Release
install:
- ps: (New-Object System.Net.WebClient).DownloadFile("https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-windows.zip", "C:\projects\hedgelib\premake.zip")
- ps: Expand-Archive -LiteralPath C:\projects\hedgelib\premake.zip -DestinationPath C:\projects\hedgelib\
- ps: Set-Content -Path C:\projects\hedgelib\hedgeedit\depends.lua -Value 'return { QtDir32 = "C:/Qt/5.11.2/msvc2015", QtDir64 = "C:/Qt/5.11.2/msvc2017_64" }'
- cmd: premake5 vs2017
build:
  project: HedgeLib.sln
  verbosity: minimal
artifacts:
- path: HedgeLib/bin/**/Release
  name: HedgeLib
- path: HedgeEdit/bin/**/Release
  name: HedgeEdit
- path: HedgeTools/HedgeArcPack/bin/**/Release
  name: HedgeArcPack